baseURL = "https://example.edu/"

languageCode = "en-us"

# for using avicenna you need to set the `themes` to 'avicenna'
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Alexander Tyurin's Biography"

[params]
# it is used for the copy-right section of your page
name = "Alexander Tyurin"
